spring:
  application:
    name: UserManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.131:3306/autotestdb?serverTimezone=GMT
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.testcy.bean
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    path: logs/UserManager.log